export const projects =
  [
    {
      title: "WePick",
      githublink: "https://github.com/jasylwong/wepick",
      websitelink: null,
      description: "An app designed to help friends choose a movie during Covid-19 isolation. Think Tinder, but for films not fiancées.",
      image: "https://i.imgur.com/8sRMy9E.gif",
      alt: "WePick example use",
      techstack: ["Ruby", "Rails", "HTML", "CSS"],
    },
    {
      title: "Covid-19 Tracker",
      githublink: "https://github.com/jlblumberg/covid-tracker",
      websitelink: "https://covid-19-data-viz.netlify.app",
      description: "A single page app for visualising real-time infection data, globally and by country.",
      image: "https://i.imgur.com/7PPyKoJ.png",
      alt: "Covid tracker example use",
      techstack: ["JavaScript", "React", "MaterialUI"],
    },
    {
      title: "Algorithmic Complexity",
      githublink: "https://github.com/jlblumberg/algorithmic-complexity",
      websitelink: null,
      description: "A complexity framework, built to measure the performance of my own algorithms against JavaScript’s inbuilt ones.",
      image: "https://i.imgur.com/krOlNl1.png",
      alt: "complexity framework example use",
      techstack: ["JavaScript", "Node.js", "Chart.js"],
    },
    {
      title: "MERN Messenger",
      githublink: "https://github.com/jlblumberg/mern-messenger",
      websitelink: null,
      description: "A minimalist message board app demonstrating TDD in the MERN Stack.",
      image: "https://i.imgur.com/rHYrzry.png",
      alt: "MERN messenger example use",
      techstack: ["JavaScript", "Node.js", "React", "Express", "MongoDB"],
    },
    {
      title: "Key-Time",
      githublink: "https://github.com/jlblumberg/hfh-groceries",
      websitelink: null,
      description: "A 2-day hackathon entry designed to help frontline workers shop safely during Covid-19.",
      image: "https://i.imgur.com/uXCItWM.png",
      alt: "key-time example use",
      techstack: ["Ruby", "Rails", "JavaScript", "Google Maps APIs"],
    },
    {
      title: "Acebook",
      githublink: "https://github.com/Peter2-71828/aceBook-PingPong",
      websitelink: null,
      description: "A clone of the similarly sounding social networking site.",
      image: "https://i.imgur.com/aoMI4WQ.png",
      alt: "Acebook example use",
      techstack: ["Ruby", "Rails", "PostgreSQL", "AWS S3"],
    },
  ]